<?php
const ISSUE_NOTES_SELECT = 'SELECT n.*, u.display_name AS created_by_name FROM issue_notes n LEFT JOIN users u ON u.id = n.created_by';
function issue_notes_to_wire($r) {
    $items = !empty($r['items']) ? json_decode($r['items'], true) : [];
    if (!is_array($items)) $items = [];
    // Backward compatibility for notes created before multi-item support.
    if (!$items && !empty($r['product_name'])) $items = [['productName'=>$r['product_name'],'quantity'=>(float)$r['quantity'],'weight'=>(float)$r['weight'],'quantityUnit'=>$r['quantity_unit'],'packaging'=>$r['packaging'],'description'=>$r['description'] ?? '']];
    return ['id'=>(int)$r['id'],'date'=>$r['date'],'dateText'=>$r['date_text'],'time'=>$r['time'],'receiverName'=>trim($r['receiver_first_name'].' '.$r['receiver_last_name']),'receiverFirstName'=>$r['receiver_first_name'],'receiverLastName'=>$r['receiver_last_name'],'customerName'=>$r['customer_name'],'items'=>$items,'createdByName'=>$r['created_by_name']??'','createdAt'=>to_iso($r['created_at']),'updatedAt'=>to_iso($r['updated_at']),'deletedAt'=>to_iso($r['deleted_at'])];
}
function issue_notes_columns($b) { $map=['date'=>'date','dateText'=>'date_text','time'=>'time','receiverFirstName'=>'receiver_first_name','receiverLastName'=>'receiver_last_name','customerName'=>'customer_name']; $o=[]; foreach($map as $a=>$z)if(array_key_exists($a,$b))$o[$z]=(string)$b[$a]; if(array_key_exists('receiverName',$b)){$o['receiver_first_name']=(string)$b['receiverName'];$o['receiver_last_name']='';} if(array_key_exists('items',$b))$o['items']=json_encode(array_values((array)$b['items']),JSON_UNESCAPED_UNICODE); return $o; }
function issue_notes_list($p,$b,$u) { $after=$_GET['updatedAfter']??null; if($after){$ts=from_iso($after);if($ts===null)json_error('Invalid updatedAfter timestamp',422);$s=db()->prepare(ISSUE_NOTES_SELECT.' WHERE n.updated_at > :ts ORDER BY n.updated_at ASC');$s->execute([':ts'=>$ts]);}else $s=db()->query(ISSUE_NOTES_SELECT.' WHERE n.deleted_at IS NULL ORDER BY n.id DESC');json_response(['issueNotes'=>array_map('issue_notes_to_wire',$s->fetchAll())]); }
function issue_notes_create($p,$b,$u) { require_fields($b,['date','customerName','items']);if(!is_array($b['items'])||!count($b['items']))json_error('At least one item is required',422);$c=issue_notes_columns($b);$now=now_utc();$c['created_by']=$u['id'];$c['updated_by']=$u['id'];$c['created_at']=$now;$c['updated_at']=$now;$f=array_keys($c);$s=db()->prepare('INSERT INTO issue_notes ('.implode(',',$f).') VALUES ('.implode(',',array_map(fn($x)=>':'.$x,$f)).')');foreach($c as $k=>$v)$s->bindValue(':'.$k,$v);$s->execute();$s=db()->prepare(ISSUE_NOTES_SELECT.' WHERE n.id=:id');$s->execute([':id'=>(int)db()->lastInsertId()]);json_response(['issueNote'=>issue_notes_to_wire($s->fetch())],201); }
function issue_notes_update($p,$b,$u) { $id=$p['id'];$q=db()->prepare('SELECT id FROM issue_notes WHERE id=:id AND deleted_at IS NULL');$q->execute([':id'=>$id]);if(!$q->fetch())json_error('Issue note not found',404);$c=issue_notes_columns($b);if(isset($b['items'])&&(!is_array($b['items'])||!count($b['items'])))json_error('At least one item is required',422);$c['updated_by']=$u['id'];$c['updated_at']=now_utc();$s=db()->prepare('UPDATE issue_notes SET '.implode(', ',array_map(fn($x)=>"$x=:$x",array_keys($c))).' WHERE id=:id');foreach($c as $k=>$v)$s->bindValue(':'.$k,$v);$s->bindValue(':id',$id);$s->execute();$s=db()->prepare(ISSUE_NOTES_SELECT.' WHERE n.id=:id');$s->execute([':id'=>$id]);json_response(['issueNote'=>issue_notes_to_wire($s->fetch())]); }
function issue_notes_delete($p,$b,$u) {$now=now_utc();$s=db()->prepare('UPDATE issue_notes SET deleted_at=:d,updated_at=:t,updated_by=:u WHERE id=:id AND deleted_at IS NULL');$s->execute([':d'=>$now,':t'=>$now,':u'=>$u['id'],':id'=>$p['id']]);if(!$s->rowCount())json_error('Issue note not found',404);json_response(['ok'=>true,'id'=>(int)$p['id']]);}
